### ISSUE TITLE
Category for blog posts

### ISSUE THREAD

**Issue by cristiandrei1234** [fictionco/fiction#130]
Hello I saw, that there is no category creation/selection in the blog section. Also a new feature could be to add custom fields and different types of archives (ex. portofolio or team).

**Comment by arpowers** [comment]
@cristiandrei1234 ah you're right, i'll put that into place later this week. 

About archives, what do you mean specifically? can you give me an example?

**Comment by cristiandrei1234** [comment]
I can give you a reference compared to WordPress to understand better what I mean->

According to WordPress Codex, “Custom Post Types” also known as “Custom Content Types” is the specific type of post types that can be added to your WordPress using a simple function called the register_post_type(). The function allows you to add the new custom post type in accordance with a number of specifics such as supported features, availability, and labels.

Or in Webflow are called CMS Collections

A collection is like a database — it's where content can be stored and referenced throughout a project dynamically. Different collections signify different content types, and an individual piece of content within a collection is called a collection item. For example, you can have a collection of blog posts, authors, clients, projects, and so on. For Ecommerce projects, you’ll also have collections for products and categories.

https://university.webflow.com/article/cms-collections

Thanks

**Comment by arpowers** [comment]
Based on those definitions Factor already has the concept of post types. That's how it does everything with a single collection. 

I can easily add category functionality to blog posts since the groundwork is already done; the option is just missing. 

If I understand you correctly,  you are just waiting to see all the plugins that Factor is going to enable... as an example we have a `jobs` plugin that looks like this: 

https://www.fiction.com/careers

On the backend it looks like this: 
<img width="1642" alt="Screen Shot 2020-02-10 at 1 29 26 PM" src="https://user-images.githubusercontent.com/308134/74187248-67510100-4c09-11ea-979b-80afbf321b43.png">


We have this and a bunch of stuff coming, if you need more detail let me know!

**Comment by cristiandrei1234** [comment]
Yes, this is what I mean.

**Comment by cristiandrei1234** [comment]
Also don`t forget Custom Fields, for the extra type of post types. 
Example to portfolio, or team, people wants to define different content than a normal blog.

**Comment by arpowers** [comment]
Sure, thats all in place already. I'd be curious to know exactly what you
are looking for... i will help you get it.

**Comment by cristiandrei1234** [comment]
I am looking at your CMS to see if it can replace WordPress in my work where it`s possible.
