### ISSUE TITLE
cannot run factor dev

### ISSUE THREAD

**Issue by caleblyn310** [fictionco/fiction#149]
Hello,

Why I can't run npx factor dev?
The error is: 

Cannot find module '@factor/loader'
Require stack:
- /home/adit/Documents/belfactor/node_modules/@factor/server/index.ts
- /home/adit/Documents/belfactor/node_modules/@factor/cli/cli.ts
- /home/adit/Documents/belfactor/node_modules/@factor/cli/index.js

And when I go to @factor folder inside <project-name>/node_modules, there is not loader folder.
This my first time install factor. I wanna try it. So, this is a fresh install. I follow every step from the documentation. So, is there any missing step that I should do? My node and npm already the latest version.

**Comment by heathism** [comment]
the same here

Ubuntu 18.04
node v12.16
npm v6.13.4

**Comment by arpowers** [comment]
hey guys/gals, many apologies. 

We just added that package and forgot to add it as a dependency. It works from within the monorepo which is why we didn't notice... 

Anyway, we've fixed that and it should be working now... let me know if the problem remains in version `1.4.9`

To rerun and make sure you're using the latest version: 

```bash
npx create-factor-app@latest
```

```bash
yarn create factor-app@latest
```

**Comment by heathism** [comment]
It's okay now.

Thanks @arpowers

**Comment by caleblyn310** [comment]
Thanks @arpowers
