### ISSUE TITLE
Could not add a new item in dashboard

### ISSUE THREAD

**Issue by siebevh** [fictionco/fiction#154]
**Reason for this issue**
Could not add a new item in dashboard (Box in my example)
**Steps to Reproduce**
repo: https://github.com/siebevh/eskapo

add this to index.ts:
```
import { addPostType } from "@factor/api"

addPostType({
	postType: "boxes",
	nameIndex: "boxes",
	nameSingle: "Box",
	namePlural: "Boxes",
	icon: require("./static/home/box.svg"), // dashboard icon
	baseRoute: "boxes", // base permalink route
	accessLevel: 1, // user access level needed to edit/add
	hideAdmin: false // Set to true to hide list/edit menu in admin
});
```

* start server
* no boxes to see in deshboard

**Comment by arpowers** [comment]
Hey there @siebevh 

Ok, found your issue, thanks for posting the repo.   There are two issues here: 

1. **Loading Config** 

In your [package.json](https://github.com/siebevh/eskapo/blob/master/package.json) you are loading  you have a syntax problem in your loading config. 

Change it to this

```json 
"load":  {
        "app": "index",
        "server": "server"
      },
```
Currently you have a object inside of an array. 

2. **hideAdmin Issue** Remove the `hideAdmin` property completely. There is a small bug in Factor that checks for `===` instead of falsy, it is getting parsed to a string ... I've fixed this already in core, but also an easy fix on your end.

**Comment by arpowers** [comment]
Note that with the load config, you can also pass an array: 
```json
"load": ["app", "server"]
```

This will load your main file (usually `index.ts`) in both the server environment and app environment.
