### ISSUE TITLE
could not add addContentRoute

### ISSUE THREAD

**Issue by siebevh** [fictionco/fiction#156]
**Reason for this issue**
I couldn't add a new ContentRoute
**Steps to Reproduce**
repo: https://github.com/siebevh/eskapo
added code in `/components/rooms/`:
```
addContentRoute({
		path: "/boxes",
		component: () => require('./box-wrap'),
	},
);
```
added box-wrap.vue
```
<template>
  <div class="work-wrap">
    <h2>TEST</h2>
    <router-view />
  </div>
</template>
```

run code and navigate to localhost:3000/boxes
no response

**Comment by arpowers** [comment]
Make sure to use `import` not require for components... 

```js
addContentRoute({
  path: "/boxes",
  component: () => import("./box-wrap.vue")
});
```

also, I recommend always using file extensions. `.vue`

Finally, images use `require` still. This is because `import` returns a promise which isn't always convenient; `require` is actually a Webpack `url-loader` thing and it just returns an image url in those cases. This doesn't work, however, with components.

**Comment by arpowers** [comment]
Also, `<router-view />` is used for nested routes. From your code, I think you're probably trying to do that.. but just making sure.
