### ISSUE TITLE
Edit factor settings from dashboard

### ISSUE THREAD

**Issue by IamSAB** [fictionco/fiction#194]
First of all, I really like to idea behind Factor and its simplistic approach, however, there are some things that are unclear to me.

I do not understand the reasoning behind:
- Why do you manage content of theme pages via factor-settings. Wouldn't it make to add the site content with a defined template to Pages what would make it easlisy customizable over the dashboard.
- Why do the menu with factor-settings? The menu is for me part of the content. And it does not make sense, if I create a page via Pages, that I have to create a menu item with factor-settings. Or it something like a menu plugin planned?

In addition, it would be great to be able to manage factor-settings in a generic way from the dashboard. Then it would make more sense, to place theme's page content and menus into factor-settings.

**Comment by arpowers** [comment]
You are correct. 

There is a reason that things don't work that way, for now. The reason is mostly because we designed Factor as a "code first then UI" platform that prioritizes the workflow of web professionals.  

That said, we've realized that a UI in those scenarios would be helpful, its actually a bit technical to do well but we have it on the near term road map.
