### ISSUE TITLE
Factor v2 - update

### ISSUE THREAD

**Issue by sstevan** [fictionco/fiction#254]
Hey @arpowers,

Great job with Factor so far! We are planning on switching to Factor (from Gatsby) for our company website.

I have noticed that you mentioned something about the Factor v2 comming up soon (in one of the latest issues)?
Can you update us on that? Should we wait for v2?

Thanks,
Stevan

**Comment by arpowers** [comment]
hey @sstevan, yes, we recommend you wait. 

Due to the switch to Vite/Vue3 we were going to have breaking changes. But in the meantime, we've learned a lot working on  [Darwin](https://www.darwin.so) so we'll also be making some really nice improvements to various architectural aspects of Factor. 

Note: Breaking changes aren't recommended for production frameworks. So with the next edition, we are striving to get to a "no breaking changes" philosophy for updates.

**Comment by sstevan** [comment]
Thanks @arpowers for the update! 

Any ETA on v2? Is it publically available on the `next` branch?

**Comment by abishekrsrikaanth** [comment]
@arpowers when can we expect v2?

**Comment by arpowers** [comment]
@abishekrsrikaanth depends on a few things that are hard to predict. Development is going faster now than ever however.

**Comment by abishekrsrikaanth** [comment]
@arpowers, good to hear. so far, have been having a lot of fun with it. Waiting to see what is in store on the new version
